# This action is currently being battle-tested in this repository.
# After stability has been proven, it should be moved to https://github.com/asyncapi/.github/

# It does magic only if there is a Dockerfile in the repository
name: Release - if Dockerfile

on:
  push:
    tags:
      - '**'

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE_NAME: asyncapi/studio
  DOCKER_PLATFORMS: linux/amd64,linux/arm64
  GIT_MAIN_BRANCH: master

jobs:

  release:
    name: Build docker image and publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set git to use LF #to once and for all finish neverending fight between Unix and Windows
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout repository
        uses: actions/checkout@v3
        id: checkout
        env:
          GIT_MAIN_BRANCH: ${{ env.GIT_MAIN_BRANCH }}
        run: |
          [ $(git rev-parse origin/$GIT_MAIN_BRANCH) = $(git rev-parse HEAD) ] && echo "::set-output name=is_main_branch::true" || "::set-output name=is_main_branch::false"
          test -e ./Dockerfile && echo "::set-output name=has_dockerfile::true" || echo "::set-output name=has_dockerfile::false"
      - if: steps.checkout.outputs.has_dockerfile == 'true'
        name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            ${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ steps.checkout.outputs.is_main_branch == 'true' }}
            type=ref,event=tag
      - if: steps.checkout.outputs.has_dockerfile == 'true'
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'linux/amd64,linux/arm64'
      - if: steps.checkout.outputs.has_dockerfile == 'true'
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - if: steps.checkout.outputs.has_dockerfile == 'true'
        name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - if: steps.checkout.outputs.has_dockerfile == 'true'
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.DOCKER_PLATFORMS }}
      - if: failure() # Only, on failure, send a message on the 94_bot-failing-ci slack channel
        name: Report workflow run status to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,action,workflow
          text: 'Release workflow failed in release job'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_FAIL_NOTIFY }}
